CREATE SEQUENCE "LICENSE_ID_seq";

CREATE TABLE "public"."LICENSE" (
    "ID" integer DEFAULT nextval('"LICENSE_ID_seq"') NOT NULL,
    "COMMENT" text,
    "ISDEPRECATED" boolean NOT NULL,
    "FSFLIBRE" boolean,
    "HEADER" text,
    "LICENSEID" character varying(255),
    "NAME" character varying(255) NOT NULL,
    "ISOSIAPPROVED" boolean NOT NULL,
    "SEEALSO" bytea,
    "TEMPLATE" text,
    "TEXT" text,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "LICENSE_LICENSEID_IDX" UNIQUE ("LICENSEID"),
    CONSTRAINT "LICENSE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "LICENSE_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);

CREATE INDEX "LICENSE_NAME_IDX" ON "public"."LICENSE" USING btree ("NAME");


CREATE SEQUENCE "LICENSEGROUP_ID_seq";

CREATE TABLE "public"."LICENSEGROUP" (
    "ID" integer DEFAULT nextval('"LICENSEGROUP_ID_seq"') NOT NULL,
    "NAME" character varying(255) NOT NULL,
    "RISKWEIGHT" integer NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "LICENSEGROUP_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "LICENSEGROUP_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);

CREATE INDEX "LICENSEGROUP_NAME_IDX" ON "public"."LICENSEGROUP" USING btree ("NAME");


CREATE TABLE "public"."LICENSEGROUP_LICENSE" (
    "LICENSEGROUP_ID" bigint NOT NULL,
    "LICENSE_ID" bigint NOT NULL,
    CONSTRAINT "LICENSEGROUP_LICENSE_FK1" FOREIGN KEY ("LICENSEGROUP_ID") REFERENCES "LICENSEGROUP"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "LICENSEGROUP_LICENSE_FK2" FOREIGN KEY ("LICENSE_ID") REFERENCES "LICENSE"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "LICENSEGROUP_LICENSE_N49" ON "public"."LICENSEGROUP_LICENSE" USING btree ("LICENSE_ID");

CREATE INDEX "LICENSEGROUP_LICENSE_N50" ON "public"."LICENSEGROUP_LICENSE" USING btree ("LICENSEGROUP_ID");
CREATE SEQUENCE "COMPONENT_ID_seq";

CREATE TABLE "public"."COMPONENT" (
    "ID" integer DEFAULT nextval('"COMPONENT_ID_seq"') NOT NULL,
    "CLASSIFIER" character varying(255),
    "COPYRIGHT" character varying(1024),
    "CPE" character varying(255),
    "DESCRIPTION" character varying(1024),
    "EXTENSION" character varying(255),
    "FILENAME" character varying(255),
    "GROUP" character varying(255),
    "INTERNAL" boolean,
    "LAST_RISKSCORE" double precision,
    "LICENSE" character varying(255),
    "MD5" character varying(32),
    "NAME" character varying(255) NOT NULL,
    "PARENT_COMPONENT_ID" bigint,
    "PURL" character varying(255),
    "LICENSE_ID" bigint,
    "SHA1" character varying(40),
    "SHA_256" character varying(64),
    "SHA3_256" character varying(64),
    "SHA3_512" character varying(128),
    "SHA_512" character varying(128),
    "UUID" character varying(36) NOT NULL,
    "VERSION" character varying(255),
    CONSTRAINT "COMPONENT_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "COMPONENT_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "COMPONENT_FK1" FOREIGN KEY ("PARENT_COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "COMPONENT_FK2" FOREIGN KEY ("LICENSE_ID") REFERENCES "LICENSE"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "COMPONENT_CLASSIFIER_IDX" ON "public"."COMPONENT" USING btree ("CLASSIFIER");

CREATE INDEX "COMPONENT_GROUP_IDX" ON "public"."COMPONENT" USING btree ("GROUP");

CREATE INDEX "COMPONENT_LAST_RISKSCORE_IDX" ON "public"."COMPONENT" USING btree ("LAST_RISKSCORE");

CREATE INDEX "COMPONENT_MD5_IDX" ON "public"."COMPONENT" USING btree ("MD5");

CREATE INDEX "COMPONENT_N49" ON "public"."COMPONENT" USING btree ("LICENSE_ID");

CREATE INDEX "COMPONENT_N50" ON "public"."COMPONENT" USING btree ("PARENT_COMPONENT_ID");

CREATE INDEX "COMPONENT_NAME_IDX" ON "public"."COMPONENT" USING btree ("NAME");

CREATE INDEX "COMPONENT_SHA1_IDX" ON "public"."COMPONENT" USING btree ("SHA1");

CREATE INDEX "COMPONENT_SHA256_IDX" ON "public"."COMPONENT" USING btree ("SHA_256");

CREATE INDEX "COMPONENT_SHA3_256_IDX" ON "public"."COMPONENT" USING btree ("SHA3_256");

CREATE INDEX "COMPONENT_SHA3_512_IDX" ON "public"."COMPONENT" USING btree ("SHA3_512");

CREATE INDEX "COMPONENT_SHA512_IDX" ON "public"."COMPONENT" USING btree ("SHA_512");


CREATE SEQUENCE "PROJECT_ID_seq";

CREATE TABLE "public"."PROJECT" (
    "ID" integer DEFAULT nextval('"PROJECT_ID_seq"') NOT NULL,
    "ACTIVE" boolean,
    "DESCRIPTION" character varying(255),
    "LAST_BOM_IMPORTED" timestamptz,
    "LAST_BOM_IMPORTED_FORMAT" character varying(255),
    "LAST_RISKSCORE" double precision,
    "NAME" character varying(255) NOT NULL,
    "PARENT_PROJECT_ID" bigint,
    "PURL" character varying(255),
    "UUID" character varying(36) NOT NULL,
    "VERSION" character varying(255),
    CONSTRAINT "PROJECT_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "PROJECT_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "PROJECT_FK1" FOREIGN KEY ("PARENT_PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "PROJECT_LASTBOMIMPORT_FORMAT_IDX" ON "public"."PROJECT" USING btree ("LAST_BOM_IMPORTED_FORMAT");

CREATE INDEX "PROJECT_LASTBOMIMPORT_IDX" ON "public"."PROJECT" USING btree ("LAST_BOM_IMPORTED");

CREATE INDEX "PROJECT_LAST_RISKSCORE_IDX" ON "public"."PROJECT" USING btree ("LAST_RISKSCORE");

CREATE INDEX "PROJECT_N49" ON "public"."PROJECT" USING btree ("PARENT_PROJECT_ID");

CREATE INDEX "PROJECT_NAME_IDX" ON "public"."PROJECT" USING btree ("NAME");

CREATE INDEX "PROJECT_VERSION_IDX" ON "public"."PROJECT" USING btree ("VERSION");


CREATE SEQUENCE "PROJECTMETRICS_ID_seq";

CREATE TABLE "public"."PROJECTMETRICS" (
    "ID" integer DEFAULT nextval('"PROJECTMETRICS_ID_seq"') NOT NULL,
    "COMPONENTS" integer NOT NULL,
    "CRITICAL" integer NOT NULL,
    "FINDINGS_AUDITED" integer,
    "FINDINGS_TOTAL" integer,
    "FINDINGS_UNAUDITED" integer,
    "FIRST_OCCURRENCE" timestamptz NOT NULL,
    "HIGH" integer NOT NULL,
    "RISKSCORE" double precision NOT NULL,
    "LAST_OCCURRENCE" timestamptz NOT NULL,
    "LOW" integer NOT NULL,
    "MEDIUM" integer NOT NULL,
    "PROJECT_ID" bigint NOT NULL,
    "SUPPRESSED" integer NOT NULL,
    "UNASSIGNED_SEVERITY" integer,
    "VULNERABILITIES" integer NOT NULL,
    "VULNERABLECOMPONENTS" integer NOT NULL,
    CONSTRAINT "PROJECTMETRICS_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "PROJECTMETRICS_FK1" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "PROJECTMETRICS_FIRST_OCCURRENCE_IDX" ON "public"."PROJECTMETRICS" USING btree ("FIRST_OCCURRENCE");

CREATE INDEX "PROJECTMETRICS_LAST_OCCURRENCE_IDX" ON "public"."PROJECTMETRICS" USING btree ("LAST_OCCURRENCE");

CREATE INDEX "PROJECTMETRICS_N49" ON "public"."PROJECTMETRICS" USING btree ("PROJECT_ID");

CREATE SEQUENCE "CWE_ID_seq";

CREATE TABLE "public"."CWE" (
    "ID" integer DEFAULT nextval('"CWE_ID_seq"') NOT NULL,
    "CWEID" integer NOT NULL,
    "NAME" character varying(255) NOT NULL,
    CONSTRAINT "CWE_CWEID_IDX" UNIQUE ("CWEID"),
    CONSTRAINT "CWE_PK" PRIMARY KEY ("ID")
) WITH (oids = false);

CREATE SEQUENCE "VULNERABILITY_ID_seq";

CREATE TABLE "public"."VULNERABILITY" (
    "ID" integer DEFAULT nextval('"VULNERABILITY_ID_seq"') NOT NULL,
    "CREATED" timestamptz,
    "CREDITS" text,
    "CVSSV2BASESCORE" numeric,
    "CVSSV2EXPLOITSCORE" numeric,
    "CVSSV2IMPACTSCORE" numeric,
    "CVSSV2VECTOR" character varying(255),
    "CVSSV3BASESCORE" numeric,
    "CVSSV3EXPLOITSCORE" numeric,
    "CVSSV3IMPACTSCORE" numeric,
    "CVSSV3VECTOR" character varying(255),
    "CWE" bigint,
    "DESCRIPTION" text,
    "PATCHEDVERSIONS" character varying(255),
    "PUBLISHED" timestamptz,
    "RECOMMENDATION" text,
    "REFERENCES" text,
    "SEVERITY" character varying(255),
    "SOURCE" character varying(255) NOT NULL,
    "SUBTITLE" character varying(255),
    "TITLE" character varying(255),
    "UPDATED" timestamptz,
    "UUID" character varying(36) NOT NULL,
    "VULNID" character varying(255) NOT NULL,
    "VULNERABLEVERSIONS" character varying(255),
    CONSTRAINT "VULNERABILITY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "VULNERABILITY_U1" UNIQUE ("VULNID", "SOURCE"),
    CONSTRAINT "VULNERABILITY_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "VULNERABILITY_FK1" FOREIGN KEY ("CWE") REFERENCES "CWE"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "VULNERABILITY_CREATED_IDX" ON "public"."VULNERABILITY" USING btree ("CREATED");

CREATE INDEX "VULNERABILITY_CWE_IDX" ON "public"."VULNERABILITY" USING btree ("CWE");

CREATE INDEX "VULNERABILITY_PUBLISHED_IDX" ON "public"."VULNERABILITY" USING btree ("PUBLISHED");

CREATE INDEX "VULNERABILITY_UPDATED_IDX" ON "public"."VULNERABILITY" USING btree ("UPDATED");

CREATE INDEX "VULNERABILITY_VULNID_IDX" ON "public"."VULNERABILITY" USING btree ("VULNID");


CREATE SEQUENCE "VULNERABILITYMETRICS_ID_seq";

CREATE TABLE "public"."VULNERABILITYMETRICS" (
    "ID" integer DEFAULT nextval('"VULNERABILITYMETRICS_ID_seq"') NOT NULL,
    "COUNT" integer NOT NULL,
    "MEASURED_AT" timestamptz NOT NULL,
    "MONTH" integer,
    "YEAR" integer NOT NULL,
    CONSTRAINT "VULNERABILITYMETRICS_PK" PRIMARY KEY ("ID")
) WITH (oids = false);


CREATE SEQUENCE "VULNERABLESOFTWARE_ID_seq";

CREATE TABLE "public"."VULNERABLESOFTWARE" (
    "ID" integer DEFAULT nextval('"VULNERABLESOFTWARE_ID_seq"') NOT NULL,
    "CPE22" character varying(255),
    "CPE23" character varying(255),
    "EDITION" character varying(255),
    "LANGUAGE" character varying(255),
    "OTHER" character varying(255),
    "PART" character varying(255),
    "PRODUCT" character varying(255),
    "PURL" character varying(255),
    "PURL_NAME" character varying(255),
    "PURL_NAMESPACE" character varying(255),
    "PURL_QUALIFIERS" character varying(255),
    "PURL_SUBPATH" character varying(255),
    "PURL_TYPE" character varying(255),
    "PURL_VERSION" character varying(255),
    "SWEDITION" character varying(255),
    "TARGETHW" character varying(255),
    "TARGETSW" character varying(255),
    "UPDATE" character varying(255),
    "UUID" character varying(36) NOT NULL,
    "VENDOR" character varying(255),
    "VERSION" character varying(255),
    "VERSIONENDEXCLUDING" character varying(255),
    "VERSIONENDINCLUDING" character varying(255),
    "VERSIONSTARTEXCLUDING" character varying(255),
    "VERSIONSTARTINCLUDING" character varying(255),
    "VULNERABLE" boolean NOT NULL,
    CONSTRAINT "VULNERABLESOFTWARE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "VULNERABLESOFTWARE_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);

CREATE INDEX "VULNERABLESOFTWARE_CPE23_VERSION_RANGE_IDX" ON "public"."VULNERABLESOFTWARE" USING btree ("CPE23", "VERSIONENDEXCLUDING", "VERSIONENDINCLUDING", "VERSIONSTARTEXCLUDING", "VERSIONSTARTINCLUDING");

CREATE INDEX "VULNERABLESOFTWARE_PART_VENDOR_PRODUCT_IDX" ON "public"."VULNERABLESOFTWARE" USING btree ("PART", "VENDOR", "PRODUCT");

CREATE INDEX "VULNERABLESOFTWARE_PURL_TYPE_NS_NAME_IDX" ON "public"."VULNERABLESOFTWARE" USING btree ("PURL_TYPE", "PURL_NAMESPACE", "PURL_NAME");

CREATE INDEX "VULNERABLESOFTWARE_PURL_VERSION_RANGE_IDX" ON "public"."VULNERABLESOFTWARE" USING btree ("PURL", "VERSIONENDEXCLUDING", "VERSIONENDINCLUDING", "VERSIONSTARTEXCLUDING", "VERSIONSTARTINCLUDING");

CREATE SEQUENCE "ANALYSIS_ID_seq";

CREATE TABLE "public"."ANALYSIS" (
    "ID" integer DEFAULT nextval('"ANALYSIS_ID_seq"') NOT NULL,
    "STATE" character varying(255) NOT NULL,
    "COMPONENT_ID" bigint,
    "PROJECT_ID" bigint,
    "SUPPRESSED" boolean NOT NULL,
    "VULNERABILITY_ID" bigint NOT NULL,
    CONSTRAINT "ANALYSIS_COMPOSITE_IDX" UNIQUE ("PROJECT_ID", "COMPONENT_ID", "VULNERABILITY_ID"),
    CONSTRAINT "ANALYSIS_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "ANALYSIS_FK1" FOREIGN KEY ("COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "ANALYSIS_FK2" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "ANALYSIS_FK3" FOREIGN KEY ("VULNERABILITY_ID") REFERENCES "VULNERABILITY"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "ANALYSIS_N49" ON "public"."ANALYSIS" USING btree ("VULNERABILITY_ID");

CREATE INDEX "ANALYSIS_N50" ON "public"."ANALYSIS" USING btree ("PROJECT_ID");

CREATE INDEX "ANALYSIS_N51" ON "public"."ANALYSIS" USING btree ("COMPONENT_ID");


CREATE SEQUENCE "ANALYSISCOMMENT_ID_seq";

CREATE TABLE "public"."ANALYSISCOMMENT" (
    "ID" integer DEFAULT nextval('"ANALYSISCOMMENT_ID_seq"') NOT NULL,
    "ANALYSIS_ID" bigint NOT NULL,
    "COMMENT" text NOT NULL,
    "COMMENTER" character varying(255),
    "TIMESTAMP" timestamptz NOT NULL,
    CONSTRAINT "ANALYSISCOMMENT_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "ANALYSISCOMMENT_FK1" FOREIGN KEY ("ANALYSIS_ID") REFERENCES "ANALYSIS"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "ANALYSISCOMMENT_N49" ON "public"."ANALYSISCOMMENT" USING btree ("ANALYSIS_ID");

CREATE SEQUENCE "TAG_ID_seq";

CREATE TABLE "public"."TAG" (
    "ID" integer DEFAULT nextval('"TAG_ID_seq"') NOT NULL,
    "NAME" character varying(255) NOT NULL,
    CONSTRAINT "TAG_PK" PRIMARY KEY ("ID")
) WITH (oids = false);


CREATE SEQUENCE "TEAM_ID_seq";

CREATE TABLE "public"."TEAM" (
    "ID" integer DEFAULT nextval('"TEAM_ID_seq"') NOT NULL,
    "NAME" character varying(50) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "TEAM_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "TEAM_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);


CREATE SEQUENCE "APIKEY_ID_seq";

CREATE TABLE "public"."APIKEY" (
    "ID" integer DEFAULT nextval('"APIKEY_ID_seq"') NOT NULL,
    "APIKEY" character varying(255) NOT NULL,
    CONSTRAINT "APIKEY_IDX" UNIQUE ("APIKEY"),
    CONSTRAINT "APIKEY_PK" PRIMARY KEY ("ID")
) WITH (oids = false);


CREATE TABLE "public"."APIKEYS_TEAMS" (
    "TEAM_ID" bigint NOT NULL,
    "APIKEY_ID" bigint NOT NULL,
    CONSTRAINT "APIKEYS_TEAMS_FK1" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "APIKEYS_TEAMS_FK2" FOREIGN KEY ("APIKEY_ID") REFERENCES "APIKEY"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "APIKEYS_TEAMS_N49" ON "public"."APIKEYS_TEAMS" USING btree ("TEAM_ID");

CREATE INDEX "APIKEYS_TEAMS_N50" ON "public"."APIKEYS_TEAMS" USING btree ("APIKEY_ID");


CREATE SEQUENCE "BOM_ID_seq";

CREATE TABLE "public"."BOM" (
    "ID" integer DEFAULT nextval('"BOM_ID_seq"') NOT NULL,
    "BOM_FORMAT" character varying(255),
    "IMPORTED" timestamptz NOT NULL,
    "PROJECT_ID" bigint NOT NULL,
    "SPEC_VERSION" character varying(255),
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "BOM_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "BOM_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "BOM_FK1" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "BOM_N49" ON "public"."BOM" USING btree ("PROJECT_ID");


CREATE TABLE "public"."BOMS_COMPONENTS" (
    "COMPONENT_ID" bigint NOT NULL,
    "BOM_ID" bigint NOT NULL,
    CONSTRAINT "BOMS_COMPONENTS_FK1" FOREIGN KEY ("COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "BOMS_COMPONENTS_FK2" FOREIGN KEY ("BOM_ID") REFERENCES "BOM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "BOMS_COMPONENTS_N49" ON "public"."BOMS_COMPONENTS" USING btree ("COMPONENT_ID");

CREATE INDEX "BOMS_COMPONENTS_N50" ON "public"."BOMS_COMPONENTS" USING btree ("BOM_ID");



CREATE SEQUENCE "COMPONENTANALYSISCACHE_ID_seq";

CREATE TABLE "public"."COMPONENTANALYSISCACHE" (
    "ID" integer DEFAULT nextval('"COMPONENTANALYSISCACHE_ID_seq"') NOT NULL,
    "CACHE_TYPE" character varying(255) NOT NULL,
    "LAST_OCCURRENCE" timestamptz NOT NULL,
    "TARGET" character varying(255) NOT NULL,
    "TARGET_HOST" character varying(255) NOT NULL,
    "TARGET_TYPE" character varying(255) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "COMPONENTANALYSISCACHE_COMPOSITE_IDX" UNIQUE ("CACHE_TYPE", "TARGET_HOST", "TARGET_TYPE", "TARGET"),
    CONSTRAINT "COMPONENTANALYSISCACHE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "COMPONENTANALYSISCACHE_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);


CREATE SEQUENCE "COMPONENTMETRICS_ID_seq";

CREATE TABLE "public"."COMPONENTMETRICS" (
    "ID" integer DEFAULT nextval('"COMPONENTMETRICS_ID_seq"') NOT NULL,
    "COMPONENT_ID" bigint NOT NULL,
    "CRITICAL" integer NOT NULL,
    "FINDINGS_AUDITED" integer,
    "FINDINGS_TOTAL" integer,
    "FINDINGS_UNAUDITED" integer,
    "FIRST_OCCURRENCE" timestamptz NOT NULL,
    "HIGH" integer NOT NULL,
    "RISKSCORE" double precision NOT NULL,
    "LAST_OCCURRENCE" timestamptz NOT NULL,
    "LOW" integer NOT NULL,
    "MEDIUM" integer NOT NULL,
    "SUPPRESSED" integer NOT NULL,
    "UNASSIGNED_SEVERITY" integer,
    "VULNERABILITIES" integer NOT NULL,
    CONSTRAINT "COMPONENTMETRICS_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "COMPONENTMETRICS_FK1" FOREIGN KEY ("COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "COMPONENTMETRICS_FIRST_OCCURRENCE_IDX" ON "public"."COMPONENTMETRICS" USING btree ("FIRST_OCCURRENCE");

CREATE INDEX "COMPONENTMETRICS_LAST_OCCURRENCE_IDX" ON "public"."COMPONENTMETRICS" USING btree ("LAST_OCCURRENCE");

CREATE INDEX "COMPONENTMETRICS_N49" ON "public"."COMPONENTMETRICS" USING btree ("COMPONENT_ID");


CREATE TABLE "public"."COMPONENTS_VULNERABILITIES" (
    "COMPONENT_ID" bigint NOT NULL,
    "VULNERABILITY_ID" bigint NOT NULL,
    CONSTRAINT "COMPONENTS_VULNERABILITIES_FK1" FOREIGN KEY ("COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "COMPONENTS_VULNERABILITIES_FK2" FOREIGN KEY ("VULNERABILITY_ID") REFERENCES "VULNERABILITY"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "COMPONENTS_VULNERABILITIES_N49" ON "public"."COMPONENTS_VULNERABILITIES" USING btree ("COMPONENT_ID");

CREATE INDEX "COMPONENTS_VULNERABILITIES_N50" ON "public"."COMPONENTS_VULNERABILITIES" USING btree ("VULNERABILITY_ID");


CREATE SEQUENCE "CONFIGPROPERTY_ID_seq";

CREATE TABLE "public"."CONFIGPROPERTY" (
    "ID" integer DEFAULT nextval('"CONFIGPROPERTY_ID_seq"') NOT NULL,
    "DESCRIPTION" character varying(255),
    "GROUPNAME" character varying(255) NOT NULL,
    "PROPERTYNAME" character varying(255) NOT NULL,
    "PROPERTYTYPE" character varying(255) NOT NULL,
    "PROPERTYVALUE" character varying(1024),
    CONSTRAINT "CONFIGPROPERTY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "CONFIGPROPERTY_U1" UNIQUE ("GROUPNAME", "PROPERTYNAME")
) WITH (oids = false);


CREATE SEQUENCE "CPE_ID_seq";

CREATE TABLE "public"."CPE" (
    "ID" integer DEFAULT nextval('"CPE_ID_seq"') NOT NULL,
    "CPE22" character varying(255),
    "CPE23" character varying(255) NOT NULL,
    "EDITION" character varying(255),
    "LANGUAGE" character varying(255),
    "OTHER" character varying(255),
    "PART" character varying(255),
    "PRODUCT" character varying(255),
    "SWEDITION" character varying(255),
    "TARGETHW" character varying(255),
    "TARGETSW" character varying(255),
    "TITLE" character varying(255),
    "UPDATE" character varying(255),
    "UUID" character varying(36) NOT NULL,
    "VENDOR" character varying(255),
    "VERSION" character varying(255),
    CONSTRAINT "CPE_CPE23_IDX" UNIQUE ("CPE23"),
    CONSTRAINT "CPE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "CPE_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);

CREATE INDEX "CPE_CPE22_IDX" ON "public"."CPE" USING btree ("CPE22");

CREATE INDEX "CPE_PRODUCT_IDX" ON "public"."CPE" USING btree ("PRODUCT");

CREATE INDEX "CPE_VENDOR_IDX" ON "public"."CPE" USING btree ("VENDOR");


CREATE SEQUENCE "CPEREFERENCE_ID_seq";

CREATE TABLE "public"."CPEREFERENCE" (
    "ID" integer DEFAULT nextval('"CPEREFERENCE_ID_seq"') NOT NULL,
    "CPE_ID" bigint,
    "HREF" character varying(2048),
    "NAME" character varying(255),
    CONSTRAINT "CPEREFERENCE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "CPEREFERENCE_FK1" FOREIGN KEY ("CPE_ID") REFERENCES "CPE"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "CPEREFERENCE_N49" ON "public"."CPEREFERENCE" USING btree ("CPE_ID");

CREATE SEQUENCE "DEPENDENCY_ID_seq";

CREATE TABLE "public"."DEPENDENCY" (
    "ID" integer DEFAULT nextval('"DEPENDENCY_ID_seq"') NOT NULL,
    "ADDED_BY" character varying(255),
    "ADDED_ON" timestamptz NOT NULL,
    "COMPONENT_ID" bigint NOT NULL,
    "NOTES" text,
    "PROJECT_ID" bigint NOT NULL,
    CONSTRAINT "DEPENDENCY_COMPOSITE_IDX" UNIQUE ("PROJECT_ID", "COMPONENT_ID"),
    CONSTRAINT "DEPENDENCY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "DEPENDENCY_FK1" FOREIGN KEY ("COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "DEPENDENCY_FK2" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "DEPENDENCY_N49" ON "public"."DEPENDENCY" USING btree ("COMPONENT_ID");

CREATE INDEX "DEPENDENCY_N50" ON "public"."DEPENDENCY" USING btree ("PROJECT_ID");


CREATE SEQUENCE "DEPENDENCYMETRICS_ID_seq";

CREATE TABLE "public"."DEPENDENCYMETRICS" (
    "ID" integer DEFAULT nextval('"DEPENDENCYMETRICS_ID_seq"') NOT NULL,
    "COMPONENT_ID" bigint NOT NULL,
    "CRITICAL" integer NOT NULL,
    "FINDINGS_AUDITED" integer,
    "FINDINGS_TOTAL" integer,
    "FINDINGS_UNAUDITED" integer,
    "FIRST_OCCURRENCE" timestamptz NOT NULL,
    "HIGH" integer NOT NULL,
    "RISKSCORE" double precision NOT NULL,
    "LAST_OCCURRENCE" timestamptz NOT NULL,
    "LOW" integer NOT NULL,
    "MEDIUM" integer NOT NULL,
    "PROJECT_ID" bigint NOT NULL,
    "SUPPRESSED" integer NOT NULL,
    "UNASSIGNED_SEVERITY" integer,
    "VULNERABILITIES" integer NOT NULL,
    CONSTRAINT "DEPENDENCYMETRICS_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "DEPENDENCYMETRICS_FK1" FOREIGN KEY ("COMPONENT_ID") REFERENCES "COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "DEPENDENCYMETRICS_FK2" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "DEPENDENCYMETRICS_COMPOSITE_IDX" ON "public"."DEPENDENCYMETRICS" USING btree ("PROJECT_ID", "COMPONENT_ID");

CREATE INDEX "DEPENDENCYMETRICS_FIRST_OCCURRENCE_IDX" ON "public"."DEPENDENCYMETRICS" USING btree ("FIRST_OCCURRENCE");

CREATE INDEX "DEPENDENCYMETRICS_LAST_OCCURRENCE_IDX" ON "public"."DEPENDENCYMETRICS" USING btree ("LAST_OCCURRENCE");

CREATE INDEX "DEPENDENCYMETRICS_N49" ON "public"."DEPENDENCYMETRICS" USING btree ("COMPONENT_ID");

CREATE INDEX "DEPENDENCYMETRICS_N50" ON "public"."DEPENDENCYMETRICS" USING btree ("PROJECT_ID");


CREATE SEQUENCE "EVENTSERVICELOG_ID_seq";

CREATE TABLE "public"."EVENTSERVICELOG" (
    "ID" integer DEFAULT nextval('"EVENTSERVICELOG_ID_seq"') NOT NULL,
    "COMPLETED" timestamptz,
    "STARTED" timestamptz,
    "SUBSCRIBERCLASS" character varying(255) NOT NULL,
    CONSTRAINT "EVENTSERVICELOG_PK" PRIMARY KEY ("ID")
) WITH (oids = false);

CREATE INDEX "SUBSCRIBERCLASS_IDX" ON "public"."EVENTSERVICELOG" USING btree ("SUBSCRIBERCLASS");


CREATE SEQUENCE "INSTALLEDUPGRADES_ID_seq";

CREATE TABLE "public"."INSTALLEDUPGRADES" (
    "ID" integer DEFAULT nextval('"INSTALLEDUPGRADES_ID_seq"') NOT NULL,
    "ENDTIME" timestamptz,
    "STARTTIME" timestamptz,
    "UPGRADECLASS" character varying(255),
    CONSTRAINT "INSTALLEDUPGRADES_PK" PRIMARY KEY ("ID")
) WITH (oids = false);


CREATE SEQUENCE "LDAPUSER_ID_seq";

CREATE TABLE "public"."LDAPUSER" (
    "ID" integer DEFAULT nextval('"LDAPUSER_ID_seq"') NOT NULL,
    "DN" character varying(255) NOT NULL,
    "USERNAME" character varying(255),
    CONSTRAINT "LDAPUSER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "LDAPUSER_USERNAME_IDX" UNIQUE ("USERNAME")
) WITH (oids = false);

CREATE SEQUENCE "PERMISSION_ID_seq";

CREATE TABLE "public"."PERMISSION" (
    "ID" integer DEFAULT nextval('"PERMISSION_ID_seq"') NOT NULL,
    "DESCRIPTION" text,
    "NAME" character varying(255) NOT NULL,
    CONSTRAINT "PERMISSION_IDX" UNIQUE ("NAME"),
    CONSTRAINT "PERMISSION_PK" PRIMARY KEY ("ID")
) WITH (oids = false);

CREATE TABLE "public"."LDAPUSERS_PERMISSIONS" (
    "LDAPUSER_ID" bigint NOT NULL,
    "PERMISSION_ID" bigint NOT NULL,
    CONSTRAINT "LDAPUSERS_PERMISSIONS_FK1" FOREIGN KEY ("LDAPUSER_ID") REFERENCES "LDAPUSER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "LDAPUSERS_PERMISSIONS_FK2" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "LDAPUSERS_PERMISSIONS_N49" ON "public"."LDAPUSERS_PERMISSIONS" USING btree ("PERMISSION_ID");

CREATE INDEX "LDAPUSERS_PERMISSIONS_N50" ON "public"."LDAPUSERS_PERMISSIONS" USING btree ("LDAPUSER_ID");


CREATE TABLE "public"."LDAPUSERS_TEAMS" (
    "TEAM_ID" bigint NOT NULL,
    "LDAPUSER_ID" bigint NOT NULL,
    CONSTRAINT "LDAPUSERS_TEAMS_FK1" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "LDAPUSERS_TEAMS_FK2" FOREIGN KEY ("LDAPUSER_ID") REFERENCES "LDAPUSER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "LDAPUSERS_TEAMS_N49" ON "public"."LDAPUSERS_TEAMS" USING btree ("LDAPUSER_ID");

CREATE INDEX "LDAPUSERS_TEAMS_N50" ON "public"."LDAPUSERS_TEAMS" USING btree ("TEAM_ID");

CREATE SEQUENCE "MANAGEDUSER_ID_seq";

CREATE TABLE "public"."MANAGEDUSER" (
    "ID" integer DEFAULT nextval('"MANAGEDUSER_ID_seq"') NOT NULL,
    "EMAIL" character varying(255),
    "FORCE_PASSWORD_CHANGE" boolean NOT NULL,
    "FULLNAME" character varying(255),
    "LAST_PASSWORD_CHANGE" timestamptz NOT NULL,
    "NON_EXPIRY_PASSWORD" boolean NOT NULL,
    "PASSWORD" character varying(255) NOT NULL,
    "SUSPENDED" boolean NOT NULL,
    "USERNAME" character varying(255),
    CONSTRAINT "MANAGEDUSER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "MANAGEDUSER_USERNAME_IDX" UNIQUE ("USERNAME")
) WITH (oids = false);


CREATE TABLE "public"."MANAGEDUSERS_PERMISSIONS" (
    "MANAGEDUSER_ID" bigint NOT NULL,
    "PERMISSION_ID" bigint NOT NULL,
    CONSTRAINT "MANAGEDUSERS_PERMISSIONS_FK1" FOREIGN KEY ("MANAGEDUSER_ID") REFERENCES "MANAGEDUSER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "MANAGEDUSERS_PERMISSIONS_FK2" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "MANAGEDUSERS_PERMISSIONS_N49" ON "public"."MANAGEDUSERS_PERMISSIONS" USING btree ("PERMISSION_ID");

CREATE INDEX "MANAGEDUSERS_PERMISSIONS_N50" ON "public"."MANAGEDUSERS_PERMISSIONS" USING btree ("MANAGEDUSER_ID");


CREATE TABLE "public"."MANAGEDUSERS_TEAMS" (
    "TEAM_ID" bigint NOT NULL,
    "MANAGEDUSER_ID" bigint NOT NULL,
    CONSTRAINT "MANAGEDUSERS_TEAMS_FK1" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "MANAGEDUSERS_TEAMS_FK2" FOREIGN KEY ("MANAGEDUSER_ID") REFERENCES "MANAGEDUSER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "MANAGEDUSERS_TEAMS_N49" ON "public"."MANAGEDUSERS_TEAMS" USING btree ("MANAGEDUSER_ID");

CREATE INDEX "MANAGEDUSERS_TEAMS_N50" ON "public"."MANAGEDUSERS_TEAMS" USING btree ("TEAM_ID");


CREATE SEQUENCE "MAPPEDLDAPGROUP_ID_seq";

CREATE TABLE "public"."MAPPEDLDAPGROUP" (
    "ID" integer DEFAULT nextval('"MAPPEDLDAPGROUP_ID_seq"') NOT NULL,
    "DN" character varying(1024) NOT NULL,
    "TEAM_ID" bigint NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "MAPPEDLDAPGROUP_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "MAPPEDLDAPGROUP_U1" UNIQUE ("TEAM_ID", "DN"),
    CONSTRAINT "MAPPEDLDAPGROUP_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "MAPPEDLDAPGROUP_FK1" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "MAPPEDLDAPGROUP_N49" ON "public"."MAPPEDLDAPGROUP" USING btree ("TEAM_ID");

CREATE SEQUENCE "OIDCGROUP_ID_seq";

CREATE TABLE "public"."OIDCGROUP" (
    "ID" integer DEFAULT nextval('"OIDCGROUP_ID_seq"') NOT NULL,
    "NAME" character varying(1024) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "OIDCGROUP_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "OIDCGROUP_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);

CREATE SEQUENCE "MAPPEDOIDCGROUP_ID_seq";

CREATE TABLE "public"."MAPPEDOIDCGROUP" (
    "ID" integer DEFAULT nextval('"MAPPEDOIDCGROUP_ID_seq"') NOT NULL,
    "GROUP_ID" bigint NOT NULL,
    "TEAM_ID" bigint NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "MAPPEDOIDCGROUP_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "MAPPEDOIDCGROUP_U1" UNIQUE ("TEAM_ID", "GROUP_ID"),
    CONSTRAINT "MAPPEDOIDCGROUP_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "MAPPEDOIDCGROUP_FK1" FOREIGN KEY ("GROUP_ID") REFERENCES "OIDCGROUP"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "MAPPEDOIDCGROUP_FK2" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "MAPPEDOIDCGROUP_N49" ON "public"."MAPPEDOIDCGROUP" USING btree ("GROUP_ID");

CREATE INDEX "MAPPEDOIDCGROUP_N50" ON "public"."MAPPEDOIDCGROUP" USING btree ("TEAM_ID");


CREATE SEQUENCE "NOTIFICATIONPUBLISHER_ID_seq";

CREATE TABLE "public"."NOTIFICATIONPUBLISHER" (
    "ID" integer DEFAULT nextval('"NOTIFICATIONPUBLISHER_ID_seq"') NOT NULL,
    "DEFAULT_PUBLISHER" boolean NOT NULL,
    "DESCRIPTION" character varying(255),
    "NAME" character varying(255) NOT NULL,
    "PUBLISHER_CLASS" character varying(1024) NOT NULL,
    "TEMPLATE" text,
    "TEMPLATE_MIME_TYPE" character varying(255) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "NOTIFICATIONPUBLISHER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "NOTIFICATIONPUBLISHER_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);


CREATE SEQUENCE "NOTIFICATIONRULE_ID_seq";

CREATE TABLE "public"."NOTIFICATIONRULE" (
    "ID" integer DEFAULT nextval('"NOTIFICATIONRULE_ID_seq"') NOT NULL,
    "ENABLED" boolean NOT NULL,
    "MESSAGE" character varying(1024),
    "NAME" character varying(255) NOT NULL,
    "NOTIFICATION_LEVEL" character varying(255),
    "NOTIFY_ON" character varying(1024),
    "PUBLISHER" bigint,
    "PUBLISHER_CONFIG" text,
    "SCOPE" character varying(255) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    CONSTRAINT "NOTIFICATIONRULE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "NOTIFICATIONRULE_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "NOTIFICATIONRULE_FK1" FOREIGN KEY ("PUBLISHER") REFERENCES "NOTIFICATIONPUBLISHER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "NOTIFICATIONRULE_N49" ON "public"."NOTIFICATIONRULE" USING btree ("PUBLISHER");


CREATE TABLE "public"."NOTIFICATIONRULE_PROJECTS" (
    "NOTIFICATIONRULE_ID" bigint NOT NULL,
    "PROJECT_ID" bigint,
    CONSTRAINT "NOTIFICATIONRULE_PROJECTS_FK1" FOREIGN KEY ("NOTIFICATIONRULE_ID") REFERENCES "NOTIFICATIONRULE"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "NOTIFICATIONRULE_PROJECTS_FK2" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "NOTIFICATIONRULE_PROJECTS_N49" ON "public"."NOTIFICATIONRULE_PROJECTS" USING btree ("NOTIFICATIONRULE_ID");

CREATE INDEX "NOTIFICATIONRULE_PROJECTS_N50" ON "public"."NOTIFICATIONRULE_PROJECTS" USING btree ("PROJECT_ID");

CREATE SEQUENCE "OIDCUSER_ID_seq";

CREATE TABLE "public"."OIDCUSER" (
    "ID" integer DEFAULT nextval('"OIDCUSER_ID_seq"') NOT NULL,
    "SUBJECT_IDENTIFIER" character varying(255),
    "USERNAME" character varying(255) NOT NULL,
    CONSTRAINT "OIDCUSER_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "OIDCUSER_USERNAME_IDX" UNIQUE ("USERNAME")
) WITH (oids = false);


CREATE TABLE "public"."OIDCUSERS_PERMISSIONS" (
    "PERMISSION_ID" bigint NOT NULL,
    "OIDCUSER_ID" bigint NOT NULL,
    CONSTRAINT "OIDCUSERS_PERMISSIONS_FK1" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "OIDCUSERS_PERMISSIONS_FK2" FOREIGN KEY ("OIDCUSER_ID") REFERENCES "OIDCUSER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "OIDCUSERS_PERMISSIONS_N49" ON "public"."OIDCUSERS_PERMISSIONS" USING btree ("OIDCUSER_ID");

CREATE INDEX "OIDCUSERS_PERMISSIONS_N50" ON "public"."OIDCUSERS_PERMISSIONS" USING btree ("PERMISSION_ID");


CREATE TABLE "public"."OIDCUSERS_TEAMS" (
    "OIDCUSERS_ID" bigint NOT NULL,
    "TEAM_ID" bigint NOT NULL,
    CONSTRAINT "OIDCUSERS_TEAMS_FK1" FOREIGN KEY ("OIDCUSERS_ID") REFERENCES "OIDCUSER"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "OIDCUSERS_TEAMS_FK2" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "OIDCUSERS_TEAMS_N49" ON "public"."OIDCUSERS_TEAMS" USING btree ("TEAM_ID");

CREATE INDEX "OIDCUSERS_TEAMS_N50" ON "public"."OIDCUSERS_TEAMS" USING btree ("OIDCUSERS_ID");

CREATE SEQUENCE "POLICY_ID_seq";

CREATE TABLE "public"."POLICY" (
    "ID" integer DEFAULT nextval('"POLICY_ID_seq"') NOT NULL,
    "NAME" character varying(255) NOT NULL,
    "OPERATOR" character varying(255) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    "VIOLATIONSTATE" character varying(255) NOT NULL,
    CONSTRAINT "POLICY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "POLICY_UUID_IDX" UNIQUE ("UUID")
) WITH (oids = false);

CREATE INDEX "POLICY_NAME_IDX" ON "public"."POLICY" USING btree ("NAME");


CREATE SEQUENCE "POLICYCONDITION_ID_seq";

CREATE TABLE "public"."POLICYCONDITION" (
    "ID" integer DEFAULT nextval('"POLICYCONDITION_ID_seq"') NOT NULL,
    "OPERATOR" character varying(255) NOT NULL,
    "POLICY_ID" bigint NOT NULL,
    "SUBJECT" character varying(255) NOT NULL,
    "UUID" character varying(36) NOT NULL,
    "VALUE" character varying(255) NOT NULL,
    CONSTRAINT "POLICYCONDITION_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "POLICYCONDITION_UUID_IDX" UNIQUE ("UUID"),
    CONSTRAINT "POLICYCONDITION_FK1" FOREIGN KEY ("POLICY_ID") REFERENCES "POLICY"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "POLICYCONDITION_N49" ON "public"."POLICYCONDITION" USING btree ("POLICY_ID");


CREATE TABLE "public"."POLICY_PROJECTS" (
    "POLICY_ID" bigint NOT NULL,
    "PROJECT_ID" bigint,
    CONSTRAINT "POLICY_PROJECTS_FK1" FOREIGN KEY ("POLICY_ID") REFERENCES "POLICY"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "POLICY_PROJECTS_FK2" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "POLICY_PROJECTS_N49" ON "public"."POLICY_PROJECTS" USING btree ("POLICY_ID");

CREATE INDEX "POLICY_PROJECTS_N50" ON "public"."POLICY_PROJECTS" USING btree ("PROJECT_ID");


CREATE SEQUENCE "PORTFOLIOMETRICS_ID_seq";

CREATE TABLE "public"."PORTFOLIOMETRICS" (
    "ID" integer DEFAULT nextval('"PORTFOLIOMETRICS_ID_seq"') NOT NULL,
    "COMPONENTS" integer NOT NULL,
    "CRITICAL" integer NOT NULL,
    "DEPENDENCIES" integer,
    "FINDINGS_AUDITED" integer,
    "FINDINGS_TOTAL" integer,
    "FINDINGS_UNAUDITED" integer,
    "FIRST_OCCURRENCE" timestamptz NOT NULL,
    "HIGH" integer NOT NULL,
    "RISKSCORE" double precision NOT NULL,
    "LAST_OCCURRENCE" timestamptz NOT NULL,
    "LOW" integer NOT NULL,
    "MEDIUM" integer NOT NULL,
    "PROJECTS" integer NOT NULL,
    "SUPPRESSED" integer NOT NULL,
    "UNASSIGNED_SEVERITY" integer,
    "VULNERABILITIES" integer NOT NULL,
    "VULNERABLECOMPONENTS" integer NOT NULL,
    "VULNERABLEDEPENDENCIES" integer,
    "VULNERABLEPROJECTS" integer NOT NULL,
    CONSTRAINT "PORTFOLIOMETRICS_PK" PRIMARY KEY ("ID")
) WITH (oids = false);

CREATE INDEX "PORTFOLIOMETRICS_FIRST_OCCURRENCE_IDX" ON "public"."PORTFOLIOMETRICS" USING btree ("FIRST_OCCURRENCE");

CREATE INDEX "PORTFOLIOMETRICS_LAST_OCCURRENCE_IDX" ON "public"."PORTFOLIOMETRICS" USING btree ("LAST_OCCURRENCE");

CREATE TABLE "public"."PROJECTS_TAGS" (
    "PROJECT_ID" bigint NOT NULL,
    "TAG_ID" bigint NOT NULL,
    CONSTRAINT "PROJECTS_TAGS_FK1" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "PROJECTS_TAGS_FK2" FOREIGN KEY ("TAG_ID") REFERENCES "TAG"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "PROJECTS_TAGS_N49" ON "public"."PROJECTS_TAGS" USING btree ("PROJECT_ID");

CREATE INDEX "PROJECTS_TAGS_N50" ON "public"."PROJECTS_TAGS" USING btree ("TAG_ID");


CREATE SEQUENCE "PROJECT_PROPERTY_ID_seq";

CREATE TABLE "public"."PROJECT_PROPERTY" (
    "ID" integer DEFAULT nextval('"PROJECT_PROPERTY_ID_seq"') NOT NULL,
    "DESCRIPTION" character varying(255),
    "GROUPNAME" character varying(255) NOT NULL,
    "PROJECT_ID" bigint NOT NULL,
    "PROPERTYNAME" character varying(255) NOT NULL,
    "PROPERTYTYPE" character varying(255) NOT NULL,
    "PROPERTYVALUE" character varying(1024),
    CONSTRAINT "PROJECT_PROPERTY_KEYS_IDX" UNIQUE ("PROJECT_ID", "GROUPNAME", "PROPERTYNAME"),
    CONSTRAINT "PROJECT_PROPERTY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "PROJECT_PROPERTY_FK1" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "PROJECT_PROPERTY_N49" ON "public"."PROJECT_PROPERTY" USING btree ("PROJECT_ID");


CREATE SEQUENCE "REPOSITORY_ID_seq";

CREATE TABLE "public"."REPOSITORY" (
    "ID" integer DEFAULT nextval('"REPOSITORY_ID_seq"') NOT NULL,
    "ENABLED" boolean NOT NULL,
    "IDENTIFIER" character varying(255) NOT NULL,
    "INTERNAL" boolean,
    "RESOLUTION_ORDER" integer NOT NULL,
    "TYPE" character varying(255) NOT NULL,
    "URL" character varying(255),
    "UUID" character varying(36),
    CONSTRAINT "REPOSITORY_COMPOUND_IDX" UNIQUE ("TYPE", "IDENTIFIER"),
    CONSTRAINT "REPOSITORY_PK" PRIMARY KEY ("ID")
) WITH (oids = false);

CREATE INDEX "REPOSITORY_UUID_IDX" ON "public"."REPOSITORY" USING btree ("UUID");


CREATE SEQUENCE "REPOSITORY_META_COMPONENT_ID_seq";

CREATE TABLE "public"."REPOSITORY_META_COMPONENT" (
    "ID" integer DEFAULT nextval('"REPOSITORY_META_COMPONENT_ID_seq"') NOT NULL,
    "LAST_CHECK" timestamptz NOT NULL,
    "LATEST_VERSION" character varying(255) NOT NULL,
    "NAME" character varying(255) NOT NULL,
    "NAMESPACE" character varying(255),
    "PUBLISHED" timestamptz,
    "REPOSITORY_TYPE" character varying(255) NOT NULL,
    CONSTRAINT "REPOSITORY_META_COMPONENT_COMPOUND_IDX" UNIQUE ("REPOSITORY_TYPE", "NAMESPACE", "NAME"),
    CONSTRAINT "REPOSITORY_META_COMPONENT_PK" PRIMARY KEY ("ID")
) WITH (oids = false);

CREATE INDEX "REPOSITORY_META_COMPONENT_LASTCHECK_IDX" ON "public"."REPOSITORY_META_COMPONENT" USING btree ("LAST_CHECK");


CREATE SEQUENCE "SCHEMAVERSION_ID_seq";

CREATE TABLE "public"."SCHEMAVERSION" (
    "ID" integer DEFAULT nextval('"SCHEMAVERSION_ID_seq"') NOT NULL,
    "VERSION" character varying(255),
    CONSTRAINT "SCHEMAVERSION_PK" PRIMARY KEY ("ID")
) WITH (oids = false);




CREATE TABLE "public"."TEAMS_PERMISSIONS" (
    "TEAM_ID" bigint NOT NULL,
    "PERMISSION_ID" bigint NOT NULL,
    CONSTRAINT "TEAMS_PERMISSIONS_FK1" FOREIGN KEY ("TEAM_ID") REFERENCES "TEAM"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "TEAMS_PERMISSIONS_FK2" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "TEAMS_PERMISSIONS_N49" ON "public"."TEAMS_PERMISSIONS" USING btree ("TEAM_ID");

CREATE INDEX "TEAMS_PERMISSIONS_N50" ON "public"."TEAMS_PERMISSIONS" USING btree ("PERMISSION_ID");




CREATE TABLE "public"."VULNERABLESOFTWARE_VULNERABILITIES" (
    "VULNERABILITY_ID" bigint NOT NULL,
    "VULNERABLESOFTWARE_ID" bigint NOT NULL,
    CONSTRAINT "VULNERABLESOFTWARE_VULNERABILITIES_FK1" FOREIGN KEY ("VULNERABILITY_ID") REFERENCES "VULNERABILITY"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE,
    CONSTRAINT "VULNERABLESOFTWARE_VULNERABILITIES_FK2" FOREIGN KEY ("VULNERABLESOFTWARE_ID") REFERENCES "VULNERABLESOFTWARE"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "VULNERABLESOFTWARE_VULNERABILITIES_N49" ON "public"."VULNERABLESOFTWARE_VULNERABILITIES" USING btree ("VULNERABILITY_ID");

CREATE INDEX "VULNERABLESOFTWARE_VULNERABILITIES_N50" ON "public"."VULNERABLESOFTWARE_VULNERABILITIES" USING btree ("VULNERABLESOFTWARE_ID");
