UPDATE "PORTFOLIOMETRICS" SET "FINDINGS_TOTAL" = 0 WHERE "FINDINGS_TOTAL" IS NULL;
UPDATE "PORTFOLIOMETRICS" SET "FINDINGS_AUDITED" = 0 WHERE "FINDINGS_AUDITED" IS NULL;
UPDATE "PORTFOLIOMETRICS" SET "FINDINGS_UNAUDITED" = 0 WHERE "FINDINGS_UNAUDITED" IS NULL;

UPDATE "PROJECTMETRICS" SET "FINDINGS_TOTAL" = 0 WHERE "FINDINGS_TOTAL" IS NULL;
UPDATE "PROJECTMETRICS" SET "FINDINGS_AUDITED" = 0 WHERE "FINDINGS_AUDITED" IS NULL;
UPDATE "PROJECTMETRICS" SET "FINDINGS_UNAUDITED" = 0 WHERE "FINDINGS_UNAUDITED" IS NULL;

UPDATE "DEPENDENCYMETRICS" SET "FINDINGS_TOTAL" = 0 WHERE "FINDINGS_TOTAL" IS NULL;
UPDATE "DEPENDENCYMETRICS" SET "FINDINGS_AUDITED" = 0 WHERE "FINDINGS_AUDITED" IS NULL;
UPDATE "DEPENDENCYMETRICS" SET "FINDINGS_UNAUDITED" = 0 WHERE "FINDINGS_UNAUDITED" IS NULL;

UPDATE "COMPONENTMETRICS" SET "FINDINGS_TOTAL" = 0 WHERE "FINDINGS_TOTAL" IS NULL;
UPDATE "COMPONENTMETRICS" SET "FINDINGS_AUDITED" = 0 WHERE "FINDINGS_AUDITED" IS NULL;
UPDATE "COMPONENTMETRICS" SET "FINDINGS_UNAUDITED" = 0 WHERE "FINDINGS_UNAUDITED" IS NULL;