DROP TABLE "PROJECT_PROPERTY";

CREATE TABLE "public"."PROJECT_PROPERTY" (
    "ID" integer DEFAULT nextval('"PROJECT_PROPERTY_ID_seq"') NOT NULL,
    "DESCRIPTION" character varying(255),
    "GROUPNAME" character varying(255) NOT NULL,
    "PROJECT_ID" bigint NOT NULL,
    "PROPERTYNAME" character varying(255) NOT NULL,
    "PROPERTYTYPE" character varying(255) NOT NULL,
    "PROPERTYVALUE" character varying(1024),
    CONSTRAINT "PROJECT_PROPERTY_KEYS_IDX" UNIQUE ("PROJECT_ID", "GROUPNAME", "PROPERTYNAME"),
    CONSTRAINT "PROJECT_PROPERTY_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "PROJECT_PROPERTY_FK1" FOREIGN KEY ("PROJECT_ID") REFERENCES "PROJECT"("ID") DEFERRABLE INITIALLY DEFERRED DEFERRABLE
) WITH (oids = false);

CREATE INDEX "PROJECT_PROPERTY_N49" ON "public"."PROJECT_PROPERTY" USING btree ("PROJECT_ID");