UPDATE "PORTFOLIOMETRICS" SET "UNASSIGNED_SEVERITY" = 0 WHERE "UNASSIGNED_SEVERITY" IS NULL;
UPDATE "PROJECTMETRICS" SET "UNASSIGNED_SEVERITY" = 0 WHERE "UNASSIGNED_SEVERITY" IS NULL;
UPDATE "DEPENDENCYMETRICS" SET "UNASSIGNED_SEVERITY" = 0 WHERE "UNASSIGNED_SEVERITY" IS NULL;
UPDATE "COMPONENTMETRICS" SET "UNASSIGNED_SEVERITY" = 0 WHERE "UNASSIGNED_SEVERITY" IS NULL;